services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "motog"
    expose:
      - "5433" # Publishes 5433 to other containers but NOT to host machine
    ports:
      - "5433:5433"
    command: -p 5433