spring:
  application:
    name: 'api-usuarios'
  jpa:
    show-sql: true
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5433/usuarios
    username: postgres
    password: motog
    driverClassName: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
server:
  port: 0

jwt:
  secret: ${JWT_SECRET:$2a$12$yBwhpMD4efu41WQzcwE.p.x/ZHvjZ0cY8ozYYwP0bBXJI/iv9UzbW}

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka