spring:
  jpa:
    show-sql: true
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/usuarios
    username: postgres
    password: motog
    driverClassName: org.postgresql.Driver

server:
  port: 8081

jwt:
  secret: ${JWT_SECRET:$2a$12$yBwhpMD4efu41WQzcwE.p.x/ZHvjZ0cY8ozYYwP0bBXJI/iv9UzbW}

